apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: oci-bv-traefik
provisioner: blockvolume.csi.oraclecloud.com
parameters:
  vpusPerGB: "10"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
