apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis-secret.yaml
  - redis-config.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-commander.yaml
